/** Человеческие подписи для кодов действий в журнале — если код не найден, показываем как есть. */
export const ACTION_LABEL: Record<string, string> = {
  'student.create': 'Добавил ученика',
  'student.update': 'Изменил данные ученика',
  'student.delete': 'Удалил ученика',
  'student.enroll': 'Перевёл ученика в группу',
  'student.reset_pin': 'Сбросил PIN ученику',
  'user.reset_pin': 'Сбросил PIN',
  'staff.create': 'Добавил сотрудника',
  'staff.update': 'Изменил данные сотрудника',
  'group.create': 'Создал группу',
  'group.update': 'Изменил группу',
  'group.archive': 'Архивировал группу',
  'group.delete': 'Удалил группу',
  'group.schedule.add': 'Добавил день в расписание группы',
  'group.schedule.remove': 'Убрал день из расписания группы',
  'payment.create': 'Принял оплату',
  'payment.update': 'Изменил оплату',
  'payment.delete': 'Удалил оплату',
  'coins.adjust': 'Скорректировал коины',
  'shop_item.create': 'Добавил товар в магазин',
  'lead.update': 'Изменил статус лида',
  'calendar_event.create': 'Создал событие в календаре',
  'calendar_event.update': 'Изменил событие в календаре',
  'calendar_event.delete': 'Удалил событие из календаря',
  'lesson.complete': 'Завершил урок',
  'lesson.cancel': 'Отменил урок',
  'lesson.attendance': 'Отметил посещаемость',
  'lesson.coins_manual': 'Начислил коины на уроке',
  'lesson.feedback': 'Оставил обратную связь по уроку',
  'homework.create': 'Задал домашку',
  'homework.review': 'Проверил домашку',
  'material.create': 'Добавил материал',
  'material.delete': 'Удалил материал',
  'order.issue': 'Выдал заказ из магазина',
  'task.create': 'Создал задачу',
  'task.update': 'Изменил задачу',
  'task.take': 'Взял задачу из пула',
  'task.release': 'Вернул задачу в пул',
  'task.delete': 'Удалил задачу',
  'task_template.create': 'Создал шаблон повторяющейся задачи',
  'task_template.update': 'Изменил шаблон повторяющейся задачи',
  'task_template.delete': 'Удалил шаблон повторяющейся задачи',
};

/** Группы для фильтра по типу действия — value это префикс action-кода. */
export const ACTION_CATEGORIES: { prefix: string; label: string }[] = [
  { prefix: 'student', label: 'Ученики' },
  { prefix: 'staff', label: 'Сотрудники' },
  { prefix: 'group', label: 'Группы' },
  { prefix: 'payment', label: 'Оплаты' },
  { prefix: 'coins', label: 'Коины' },
  { prefix: 'shop_item', label: 'Магазин' },
  { prefix: 'lead', label: 'Лиды' },
  { prefix: 'calendar_event', label: 'Календарь' },
  { prefix: 'lesson', label: 'Уроки' },
  { prefix: 'homework', label: 'Домашки' },
  { prefix: 'material', label: 'Материалы' },
  { prefix: 'order', label: 'Заказы' },
  { prefix: 'task', label: 'Задачи' },
];
